version: "3.8"

services:
  listener1:
    build: .
    container_name: listener_1
    environment:
      - PORT=5001
      - MONGO_URI=${MONGO_URI}
      - REDIS_URL=redis://redis:6379
    ports:
      - "5001:5001"
    depends_on:
      - redis
    restart: unless-stopped

  listener2:
    build: .
    container_name: listener_2
    environment:
      - PORT=5002
      - MONGO_URI=${MONGO_URI}
      - REDIS_URL=redis://redis:6379
    ports:
      - "5002:5002"
    depends_on:
      - redis
    restart: unless-stopped

  listener3:
    build: .
    container_name: listener_3
    environment:
      - PORT=5003
      - MONGO_URI=${MONGO_URI}
      - REDIS_URL=redis://redis:6379
    ports:
      - "5003:5003"
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: fantacode_redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  nginx:
    image: nginx:alpine
    container_name: fantacode_nginx
    ports:
      - "5000:5000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - listener1
      - listener2
      - listener3

volumes:
  redis-data:
